server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yojhaira/Proyecto-I
          username:  {GET_USER}
          password:  {GET_PWS}
          search-paths: /
          default-label: "main"

  security:
    user:
      name: root
      password: s3cr3t
